
"use client";

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Sparkles, BrainCircuit, Calendar } from 'lucide-react';
import { aiMatchStorytellerPreviews, AIMatchStorytellerPreviewsOutput } from '@/ai/flows/ai-match-storyteller-previews-flow';

export function Storyteller() {
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState<AIMatchStorytellerPreviewsOutput | null>(null);

  const generateAnalysis = async () => {
    setLoading(true);
    try {
      const result = await aiMatchStorytellerPreviews({
        team1Name: "FC Tinghir",
        team2Name: "Rival Stars",
        matchDate: "2026-06-15",
        context: "The Grand Opening Match of the Season"
      });
      setAnalysis(result);
    } catch (error) {
      console.error("AI Analysis failed", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <section className="py-24 bg-background">
      <div className="max-w-4xl mx-auto px-6">
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 text-primary font-bold text-sm mb-4">
            <Sparkles size={16} />
            AI-POWERED INSIGHTS
          </div>
          <h2 className="text-3xl md:text-4xl font-headline font-bold mb-4">AI Match Storyteller</h2>
          <p className="text-muted-foreground">
            Get exclusive tactical summaries and match previews generated by our specialized AI engine.
          </p>
        </div>

        <Card className="glass-card border-primary/20 overflow-hidden">
          <CardHeader className="bg-primary/5 border-b border-primary/10">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <BrainCircuit className="text-primary" />
                <CardTitle className="text-lg">Live Tactical Engine</CardTitle>
              </div>
              <div className="flex items-center gap-2 text-xs text-muted-foreground">
                <Calendar size={14} />
                Match: June 15, 2026
              </div>
            </div>
          </CardHeader>
          <CardContent className="p-8">
            {!analysis ? (
              <div className="text-center py-12">
                <p className="text-muted-foreground mb-8">
                  Witness the power of our AI analyzing the upcoming derby match between FC Tinghir and Rival Stars.
                </p>
                <Button 
                  onClick={generateAnalysis} 
                  disabled={loading}
                  className="bg-primary hover:bg-accent h-12 px-8 rounded-full glow-red glow-red-hover"
                >
                  {loading ? "Analyzing Field Data..." : "Generate Match Preview"}
                </Button>
              </div>
            ) : (
              <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
                <div>
                  <h4 className="font-headline font-bold text-primary mb-2 flex items-center gap-2">
                    <Sparkles size={16} /> Preview
                  </h4>
                  <p className="text-muted-foreground leading-relaxed italic">
                    "{analysis.matchPreview}"
                  </p>
                </div>
                <div className="p-4 rounded-lg bg-white/5 border border-white/10">
                  <h4 className="font-headline font-bold text-white mb-2">Tactical Summary</h4>
                  <p className="text-muted-foreground text-sm leading-relaxed">
                    {analysis.tacticalSummary}
                  </p>
                </div>
                <Button variant="ghost" onClick={() => setAnalysis(null)} className="text-xs">
                  Reset Analysis
                </Button>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </section>
  );
}
